### ISSUE TITLE
2. About Me Akhil

### ISSUE THREAD

**Issue by SlimeyTurtles** [SlimeyTurtles/Rat-Homework#2]
Create an About me for Akhil

[Git Hub Link](https://github.com/SlimeyTurtles/Rat-Homework/blob/main/templates/akhil.html)

**Comment by AkhilNandhakumar** [comment]
[https://github.com/SlimeyTurtles/Rat-Homework/commit/057f58a737a98a88208331f18e54ecd7ce929877](https://github.com/SlimeyTurtles/Rat-Homework/commit/057f58a737a98a88208331f18e54ecd7ce929877)

**Comment by AkhilNandhakumar** [comment]
[about me commit](https://github.com/SlimeyTurtles/Rat-Homework/commit/057f58a737a98a88208331f18e54ecd7ce929877)
