### ISSUE TITLE
4. Ideate Theme

### ISSUE THREAD

**Issue by SlimeyTurtles** [SlimeyTurtles/Rat-Homework#20]
Brainwrite/Update Wireframe for a theme and for a minilab location

**Tangibles:**
[Wireframe Initial](https://docs.google.com/drawings/d/13SSeENyirBK6gFAlrlJrfwtCf8htn690_FfCfaHr6hg/edit?usp=sharing)
[Revised Menu wireframe + theme + theme brainwrite](https://docs.google.com/drawings/d/1EhY_meu3FENJRA6Q3lh0G19nPU1qK4Fv9JI6G1Pp7vg/edit?usp=sharing)

**Comment by AkhilNandhakumar** [comment]
**Tangibles:**
[Wireframe Initial](https://docs.google.com/drawings/d/13SSeENyirBK6gFAlrlJrfwtCf8htn690_FfCfaHr6hg/edit?usp=sharing)
[Revised Menu wireframe + theme + theme brainwrite](https://docs.google.com/drawings/d/1EhY_meu3FENJRA6Q3lh0G19nPU1qK4Fv9JI6G1Pp7vg/edit?usp=sharing)
[Calissa Theme Commits](https://github.com/SlimeyTurtles/Rat-Homework/commit/605aaea7ced436e449cb6fe55cbad204a7c9025b)
