### ISSUE TITLE
Teacher Review Week 4

### ISSUE THREAD

**Issue by SlimeyTurtles** [SlimeyTurtles/Rat-Homework#28]

**Comment by Ritvik-Keerthi** [comment]
Individual Commits for Week 4 Sprint:

Akhil - Binary work and individual commit of creating the bootstrap grid is given for a technical. Good amount of work done in terms of commits and added lines. (Individual Grade - 2/2)

Avinh - Readme and Scrumboard made to look polished this week. As for a technical, a drop-up for the menu was created, showing good work done as well. (Individual Grade - 2/2)

Calissa - Binary hackathon technical is clearly shown along with the changing of theme on the website. Individual commits are shown correctly and look good. (Individual Grade - 2/2)

Journals are very easy to navigate, with bookmarks added in the document to navigate to the proper titles. Overall, the journals are neat and look great.

**Comment by Ritvik-Keerthi** [comment]
Team Commits for Week 4 Sprint (Team Grades):

Planning: Good planning demonstrated by a neat README as well as an organized Scrum Board (1/1)

Team Technicals: Good showing of all the technicals in the 2 minute video. All 4 team members did pretty good work in Week 4. (2/2)

Overall Score: 5/5 for all team members.
