### ISSUE TITLE
10. Navbar Dropdown

### ISSUE THREAD

**Issue by SlimeyTurtles** [SlimeyTurtles/Rat-Homework#7]
Bootstrap drop downs in navbar, start to form Wire Frame menu options.  Each menu option should have a Stub code page

[Link to Commit](https://github.com/SlimeyTurtles/Rat-Homework/commit/069a02d2707d03a521e396e73df8ddd68c0db6b0)

**Comment by AkhilNandhakumar** [comment]
[bootstrap dropdown commit](https://github.com/SlimeyTurtles/Rat-Homework/commit/069a02d2707d03a521e396e73df8ddd68c0db6b0)
