### ISSUE TITLE
11. Video Journal 0

### ISSUE THREAD

**Issue by SlimeyTurtles** [SlimeyTurtles/Rat-Homework#8]
Create a button on the navbar that leads to a page with Video Journal 0

[Link](https://github.com/SlimeyTurtles/Rat-Homework/blob/main/templates/videojournal.html)

**Comment by AkhilNandhakumar** [comment]
[Video Journal commit](https://github.com/SlimeyTurtles/Rat-Homework/commit/d081f971072255638e13b1d2f4a377cc81e144fe)
